### ISSUE TITLE
Make unit tests work in Python 2.6

### ISSUE THREAD

**Issue by egor045** [makhidkarun/ehex#1]
```
    def test_assign_invalid(self):
        '''Test invalid assignments'''
>       with self.assertRaises(ValueError):
            value = ehex(-1)
E           TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
```

```
    def test_addition_result_type(self):
        '''Test addition returns ehex'''
>       self.assertIsInstance(ehex(3) + 3, ehex)
E       AttributeError: 'TestEHexAddition' object has no attribute 'assertIsInstance'
```

**Comment by LeamHall** [comment]
Do we want to ask the CoTI coder community to talk about supported versions? I don't know the Level of Effort off the top of my head for this, but if it's huge then is it better to say "we can support versions X, Y, and Z"? I know at least one person is runing python 2.5, so it seems to be a discussion item.

**Comment by egor045** [comment]
Python 2.6 unittest.TestCase lacks assertIsInstance() and doesn't support the useful 'with self.assertRaises(exception):' construction. Unit tests now branch to v2.6 syntax if running Python 2.6 or earlier. I can confirm they pass using Python 2.6, 2.7 and 3.5.

It'd be worthwhile discussing supported versions on CoTI. The oldest Python version travis-ci.org supports is 2.6, so we'd need to build some kind of CI environment ourselves for older versions.

The advantage of remote REST APIs is that we can keep the API servers current and let the older clients take care of their own code. I'll bet that comes up in any discussion :)

**Comment by LeamHall** [comment]
This seems to work for the py_tools repo:

https://github.com/makhidkarun/py_tools/blob/master/.travis.yml

**Comment by egor045** [comment]
Works for ehex too

**Comment by egor045** [comment]
Closing, nothing more to see here
